### ISSUE TITLE
Feature Request: add api list feature

### ISSUE THREAD

**Issue by Ebrehe** [xenia-manager/xenia-manager#100]
**Is your feature request related to a problem? Please describe.**
writing api address manually frustrating

**Describe the solution you'd like**
Get the API list from the config to the UI, as in the photo
![Untitled](https://github.com/user-attachments/assets/b8c85c6a-fefe-443d-b3e8-25d357dcdc65)

**Comment by shazzaam7** [comment]
I have implemented this in the latest [experimental build](https://github.com/xenia-manager/xenia-manager/releases/tag/experimental).
