### ISSUE TITLE
[Feature Request] Mousehook Build Support

### ISSUE THREAD

**Issue by A1eNaz** [xenia-manager/xenia-manager#101]
as title says, would like there to be mousehook build to be integrated with the app. [maybe mousehook netplay support aswell?]

link to the normal builds here: https://github.com/Clippy95/xenia-canary-mousehook
link to the netplay builds here: https://github.com/Clippy95/xenia-canary-mousehook/releases?q=netplay&expanded=true

i wonder if its also possible to change or add binds in the settings for the app? [like multiple binds akin to steam controller config.]
[i wrote a method](https://github.com/A1eNaz/Xenia-Settings/wiki#how-do-i-use-mouse--keyboard-for-xenia) on changing or adding binds for non-supported or existing games with the bindings.ini file.

**Comment by shazzaam7** [comment]
I am going to add this eventually, but for now the 3 builds that are supported work just fine and this one could be used as a custom version for now since is ~20 games (Unless I'm mistaken).

**Comment by Dangel98** [comment]
>  this one could be used as a custom version for now.
When I try to use it as a custom version it fails to load the bindings.ini

**Comment by shazzaam7** [comment]
> When I try to use it as a custom version it fails to load the bindings.ini

![xenia_canary_bUdynk3y3r](https://github.com/user-attachments/assets/6ac3990d-69be-4a42-8eef-5310b8ebd5ec)

Thanks for notifying me about that. I'm pretty sure I fixed this in the [dev build](https://github.com/xenia-manager/xenia-manager/releases/tag/experimental) (I have only tested it with Perfect Dark). Can you please test it and let me know if I fixed it?

**Comment by Dangel98** [comment]
Yes, it loads for both, Perfect Dark and Goldeneye. Unfortunately I can't apply game patches after switching to Mousehook. I'm a noob so I have no idea if this is obviously not possible because of the other build of Xenia or if the option in the drop-down menu is missing.

**Comment by shazzaam7** [comment]
> Yes, it loads for both, Perfect Dark and Goldeneye. Unfortunately I can't apply game patches after switching to Mousehook. I'm a noob so I have no idea if this is obviously not possible because of the other build of Xenia or if the option in the drop-down menu is missing for another reason.

It's because you're using "Custom" version of Xenia, so you will have to do it yourself sadly.
I will add Mousehook support at some point, just waiting for them to do a big merge before doing it.

**Comment by shazzaam7** [comment]
Implemented in the prerelease of v2.0.0
