### ISSUE TITLE
Feature Request: Use Game Executable Icon

### ISSUE THREAD

**Issue by ElTioRata** [xenia-manager/xenia-manager#106]
Currently, Xenia Manager grabs game's box art and crops it to turn it into an icon. Some people may like this but I think it's more preferable if it just grabbed the icon stored in the game's default.xex

**Comment by shazzaam7** [comment]
Re-add the game, and it will grab the proper icon from the source (if you choose Xbox Marketplace or Launchbox Database).

I am working on getting the icon parsed, but the problem is what if the user added the game in a different format?

**Comment by shazzaam7** [comment]
Closing this issue since icons are added with the sources (At worst it will add the default disc as an shortcut icon). I will try to get the icon parsed from the game files. It's on my TODO list.
