### ISSUE TITLE
Pure 2008 - Could not find a part of the path '...\Pure.config.toml'

### ISSUE THREAD

**Issue by Mohammed-Mounir** [xenia-manager/xenia-manager#107]
**Describe the bug**
When attempting to add the game "Pure (2008)" and download the box art, the following issues occur:

Upon clicking the game name to download the box art, an error message appears:

"Could not find a part of the path '...\Pure.config.toml'."
When attempting to close the interface, a confirmation message asks whether to add the game without the box art:

If I click "No": The interface closes, but no further action is taken.
If I click "Yes": The same error message reappears:
"Could not find a part of the path '...\Pure.config.toml'."

![1](https://github.com/user-attachments/assets/53dabe2b-ef41-4f38-85c4-b52744ed6509)
![2](https://github.com/user-attachments/assets/214f83cd-5861-43ab-b8b7-d797b7eaedb4)

**Comment by shazzaam7** [comment]
I need Xenia Manager log file

**Comment by Mohammed-Mounir** [comment]
> I need Xenia Manager log file, otherwise I can't do much.

[Log-20240821.txt](https://github.com/user-attachments/files/16691111/Log-20240821.txt)

**Comment by shazzaam7** [comment]
Does this happen for other games too?

**Comment by Mohammed-Mounir** [comment]
No, other works fine.

**Comment by shazzaam7** [comment]
'E:\1 Emulators\Xbox 360\xenia_manager\Xenia Canary\config\Pure.config.toml' Can you check every folder exists in this path.

**Comment by shazzaam7** [comment]
That's odd, can you create it yourself and then try to add the game?

**Comment by Mohammed-Mounir** [comment]
Okay, so I created an empty config folder within Xenia Canary

![3](https://github.com/user-attachments/assets/4250c62b-2dfe-49a5-a9d0-968b750b927d)

and I tried adding the game again, it added the box art without any issue!

![5](https://github.com/user-attachments/assets/2cfcf4fa-a84a-46c0-a248-7a8378f10b8a)

I checked the empty config folder and found it created Pure.config.toml file

![4](https://github.com/user-attachments/assets/55258de3-67f0-422a-8da1-269f048f8236)

Thanks a lot

**Comment by shazzaam7** [comment]
Really weird what happened there. I'm checking the code right now and it should've created that folder when it installed Xenia Canary. I've just now reinstalled the Xenia Canary 3 times on 2 different machines (Windows and Linux) and every time it also created that folder.

**Comment by shazzaam7** [comment]
I'll close this issue now, but I'll keep a close eye on it in case it happens again.
