### ISSUE TITLE
App wont launch

### ISSUE THREAD

**Issue by ZaZaNonStop** [xenia-manager/xenia-manager#110]
**Describe the bug**

When I downloaded xenia manager, I can't get it to launch after double clicking the app. Xenia works fine but manager isn't working for me. 

https://github.com/user-attachments/assets/c4846bbf-9d6c-477c-9690-e780fd84e664

**Log File**
In the video I didn't see the app in event logger, or I was in the wrong location, I'm not sure.

**Comment by shazzaam7** [comment]
Do you have .NET Desktop Runtime?

**Comment by ZaZaNonStop** [comment]
I just downloaded it. I'll see if I can figure out how to debug it later tonight.

**Comment by ZaZaNonStop** [comment]
I got it to work. Thanks for the help
