### ISSUE TITLE
Xenia folder selection

### ISSUE THREAD

**Issue by Solitair69** [xenia-manager/xenia-manager#114]
pls let us select target folder of xenia/canary
or accept same folder 
but not subfolder

**Comment by shazzaam7** [comment]
I need more information otherwise I'll close this issue/feature request due to lack of details.

**Comment by Solitair69** [comment]
oh sorry,
i mean xenia manager only finds xenia if its in an subfolder from its position
would be nice it also finds it when its in the same folder or lets the target folder be picked

**Comment by shazzaam7** [comment]
If you want to use Custom Xenia version you can do that by adding the game to Xenia Manager and then going into "Edit Game" and choosing the option "Switch to Custom Xenia".
