### ISSUE TITLE
not really a bug but where can we tell you if a game is playable or not?

### ISSUE THREAD

**Issue by A1eNaz** [xenia-manager/xenia-manager#119]
what the title says

**Comment by markjfine** [comment]
Should be a small emoji on upper left corner of the game image.

**Comment by shazzaam7** [comment]
The way this detects if the game is playable is by parsing it's issue page on game-compatibility. I have plans on creating something like ProtonDB where users can submit their results (as an alternative way of game-compatibility repo) and then using that, but can't promise much.
