### ISSUE TITLE
Feature Request: Add --fullscreen launch argument

### ISSUE THREAD

**Issue by ElTioRata** [xenia-manager/xenia-manager#125]
Close this issue if this is already implemented. It'd be nice to add a launch argument that starts the game in full screen like the one that already provides the emulator.

**Comment by A1eNaz** [comment]
![image](https://github.com/user-attachments/assets/268e6c8c-47c0-455c-a8ba-f9d03ad29fd5)

**Comment by shazzaam7** [comment]
Yeah, already implemented.

**Comment by ElTioRata** [comment]
I was either blind or I forgot to apply settings 😬 Thx
