### ISSUE TITLE
Suggestion: Add version number of manager

### ISSUE THREAD

**Issue by ChewableChewy23** [xenia-manager/xenia-manager#126]
Probably just a me issue, but i get that "i need to install again to make sure" feeling when a new update for the manager is added.

Anyway to add a version number either in settings or just on the window?

Sidenote: I am super new to github and apologize if i posted this incorrectly, are tags added by someone else? Thanks all

**Comment by shazzaam7** [comment]
I'm struggling to understand the issue.

**Comment by ChewableChewy23** [comment]
apologies, was trying to ask if there can be a version number added anywhere to the manager

**Comment by shazzaam7** [comment]
Added in #133. When you open "Xenia Manager Settings", in the Title Text it will say the version you are currently on.
Example: Xenia Manager v1.13.2
