### ISSUE TITLE
 "process with an id of _ is not running"

### ISSUE THREAD

**Issue by soundsofsilence** [xenia-manager/xenia-manager#129]
**Describe the bug**

When I try to add NFL Head Couch 09, I get the message "process with an id of (changing four digit numbers like 3048) is not running." The game works perfectly as usual, but I get the message after closing Xenia Canary, and it doesn't appear in Xenia-Manager.

**To Reproduce**

Attempt to add the game as usual and exit.

**Expected behavior**

Be added to the library.

**Screenshots/Video**

![image](https://github.com/user-attachments/assets/1e611466-26aa-49c6-9fa4-02cc759380cb)

**Log File**

  - Xenia Manager Log: https://gist.github.com/soundsofsilence/45c67870b7df9863f0a3581885d67b97
  - Xenia Log: https://gist.github.com/soundsofsilence/fd53574d9fa25022c3215b65143ff1df

**Comment by shazzaam7** [comment]
Does it happen with other games or just this one?

**Comment by soundsofsilence** [comment]
I found the reason: Xenia Manager must be run as an administrator.

**Comment by shazzaam7** [comment]
In what directory do you have Xenia Manger? I would recommend putting it somewhere that doesn't need admin rights like Desktop or AppData etc.

**Comment by soundsofsilence** [comment]
> In what directory do you have Xenia Manger? I would recommend putting it somewhere that doesn't need admin rights like Desktop or AppData etc.

It's not in a protected folder. To avoid such situations, I place all my games in C:\Games. I also tried disabling my antivirus to ensure there were no false positives, but it made no difference.
