### ISSUE TITLE
Pls add  "d3d12_allow_variable_refresh_rate_and_tearing " to settings

### ISSUE THREAD

**Issue by Solitair69** [xenia-manager/xenia-manager#132]
In  Xenia discord i learned that this is the real value for getting rid of extreme Tearing
instead of vsync
setting
d3d12_allow_variable_refresh_rate_and_tearing to false
i have tested  this and works perfect

**Comment by shazzaam7** [comment]
This setting is already implemented in Xenia Manager under the name "Variable Refresh Rate (Direct3D 12)"
