### ISSUE TITLE
[Feature Request] Patch Auto-Updater

### ISSUE THREAD

**Issue by A1eNaz** [xenia-manager/xenia-manager#141]
what the title says, something akin to the Canary Auto-Updater embedded in the Manager or RPCS3's Patch Manager.

**Comment by shazzaam7** [comment]
I have added this feature in the [dev build](https://github.com/xenia-manager/xenia-manager/releases/tag/experimental).
It's just using SHA to check if it's different and if it is, it will add an option "Update Patch" in "Patch Settings".

I have been testing this by just changing something in the file and then refreshing the library and it seemed to work. Will have to wait and see for some patch to get updated.

**Comment by SantiiRepair** [comment]
I would like to help with the interface but my imagination sucks, if someone has a figma design or something like that I would appreciate it and I would make a PR no problem.
