### ISSUE TITLE
[Feature Request] Optional "Update to dev build"

### ISSUE THREAD

**Issue by soundsofsilence** [xenia-manager/xenia-manager#145]
The only way to use the latest dev builds is to manually download them. Please add an option to download dev builds in Settings. 
Thanks!

**Comment by shazzaam7** [comment]
That's the point of dev builds, they're there only for testing and should not be daily driven. If they were Beta releases then I would've added an option, but with dev builds I really don't want to add it considering they can be really unstable.

**Comment by soundsofsilence** [comment]
But that's why it should be optional and disabled by default. If the dev builds are easily accessible, more people will playtest them. Not to mention, Xenia Canary is a dev build anyway.

**Comment by shazzaam7** [comment]
For me, Dev builds are more to just let the user know that the feature has been added and that he can test it in a separate enviroment.
Also I've made them only have 1 release that is always being updated (More like constantly deleted and then created again using the same tag) so tracking them would be impossible. I would have to create a new repository that stores their releases.
