### ISSUE TITLE
[Bug] Pinball FX does not show up in list of games when adding to Xenia Manger. 

### ISSUE THREAD

**Issue by NuclearGeneral** [xenia-manager/xenia-manager#148]
## Describe the bug

Pinball FX does not show up in list of games when adding to Xenia Manger.  Xenia Manager thinks Pinball FX is Pinball FX2. I cannot get Xenia Manager to add the game as Pinball FX. I do not have Pinball FX2.

## To Reproduce
1. Go to '...' Add Game
2. Click on '....' Add Pinball FX

![Xenia Pinball error 1](https://github.com/user-attachments/assets/d0531950-6120-4ff4-ad84-69aa620239cb)

![Xenia Pinball error 2](https://github.com/user-attachments/assets/c5d571ea-9683-4700-bc78-2033eb1d0765)

## Environment Information

- OS: 
- App Version: 

## Log File

- Xenia Manager Log: [Pastebin link]()
- Xenia Log: [Pastebin link]()

**Comment by shazzaam7** [comment]
I see. It's not a bug in Xenia Manager, but in Xbox source. For now, you can remame the game and possibly download the new artwork for the game from some sources like mobygames, etc. I'll let you know when I have fixed this in the database.

**Comment by shazzaam7** [comment]
I have fixed this. Let me know if it's working for you now. (Might take some time before the changes show up)

**Comment by NuclearGeneral** [comment]
The game did show up correctly this time! Thank you SOO MUCH for the quick reply and fix for this game!! Thank you! xD
