### ISSUE TITLE
[Feature Request] Add option to backup game saves before launch

### ISSUE THREAD

**Issue by CyferV** [xenia-manager/xenia-manager#157]
Automatically backup saves when launching game using xenia manager or manager created shortcut.
Preferably store backups in xenia manager subfolder or custom directory rather then desktop.
Possibly enable/disable feature per game. Main purpose is to prevent save corruption considering  current xenia state.

**Comment by shazzaam7** [comment]
I was going to add this in 1.15.0, but I ended up delaying it because there is some work being done that might affect this so I ended up delaying until it's released.

**Comment by shazzaam7** [comment]
### Small update on this feature request

How I'm most likely going to make this feature is by having the user select which profile slot (1-4) he wants to have automatic backups enabled (by default it will backup Profile Slot 1).

**Comment by shazzaam7** [comment]
Added in v2.0.0
