### ISSUE TITLE
[Help] 

### ISSUE THREAD

**Issue by chicodr** [xenia-manager/xenia-manager#158]
![Bild_2024-10-02_164610221](https://github.com/user-attachments/assets/897f2875-caaa-43b0-a305-6b278545a7a5)

I try to add the game but it doesn't work.

**Comment by shazzaam7** [comment]
I've tried it on 2 of my systems, both work fine. Try reinstalling Xenia

**Comment by chicodr** [comment]
> I've tried it on 2 of my systems, both work fine. Try reinstalling Xenia

I did multiple times. even reset my whole PC ( it was about time ) still doesn't work.

**Comment by shazzaam7** [comment]
Send log file

**Comment by chicodr** [comment]
[Log-20241002.txt](https://github.com/user-attachments/files/17231334/Log-20241002.txt)


> Send log file

**Comment by shazzaam7** [comment]
Try using Xenia Canary

**Comment by chicodr** [comment]
so now i seemed to identify all issues but still came across a new one.

Add Game -> Game.Iso -> Stable / Canary -> 

![Bild_2024-10-02_181746993](https://github.com/user-attachments/assets/78d57155-ab95-4b74-9072-5485cd795646)

**Comment by chicodr** [comment]
it just keeps my mouse cursour on loading and keeps telling me this

**Comment by shazzaam7** [comment]
Can you check if that icon file is actually downloaded? If not, delete installedGames.JSON and try to re add the game, also send me the log file (use rentry.org to paste the log file)

**Comment by chicodr** [comment]
nvm i deleted installedGames.json, un- adn reinstalled xenia and now games are added. thanks anyway bro.

**Comment by shazzaam7** [comment]
Sorry for the trouble. Sadly I couldn't replicate it on my 2 setups

**Comment by chicodr** [comment]
btw i had to manually download vcruntime140_1.dll and msvcp140.dll manually bc they were missing for some reason.

and other question is; is xenia backwards compatible? (wanna play xbox classic games prolly)

thank you so much for your help
