### ISSUE TITLE
[Feature Request] Support for Xenia Netplay Version

### ISSUE THREAD

**Issue by SiriusVI87** [xenia-manager/xenia-manager#159]
I would like to see support for the netplay version of Xenia, since quite a few games only work correctly with emulated netplay:

https://github.com/AdrianCassar/xenia-canary

Hope this will be picked up in the future.

Thx for our consideration!

**Comment by shazzaam7** [comment]
Already implemented, although it's only using "stable" releases and not the absolute latest builds from the github actions.

**Comment by SiriusVI87** [comment]
Oh wow, this is awesome. Didn't know about that =). Just tried it and it works like a charm!
