### ISSUE TITLE
[Bug] Picking custom box art doesn't work correctly

### ISSUE THREAD

**Issue by NoDowt** [xenia-manager/xenia-manager#163]
When editing an added game to select a different boxart image, it is not being saved correctly.

1. Right Click on a game 
2. Select 'Edit Game Details'
3. Click on the Boxart Image
4. Select a new image to be used & click open
5. Image stays as the previous boxart not the new one

## Expected behavior
Boxart image should be updated correctly.
It appears that the imported image is being named incorrectly (missing ' Boxart' being appended to the game name) when saved to the icons folder; or the installedGames.json is not being updated with the new file name.

## Screenshots/Video
![image](https://github.com/user-attachments/assets/b804ae61-5603-4ff4-8861-ab3cd84ff4d6)

## Environment Information
- OS: Windows 11
- App Version: v1.15.0

## Additional context
Deleting the original boxart.ico file & renaming the newly created file to have ' Boxart' appended fixes the issue.

Alternatively, you could edit the filename referenced in installedGames.json. This would keep the original ' Boxart' file & allow a rollback option to be added?

**Comment by shazzaam7** [comment]
I've fixed this in the [dev build](https://github.com/xenia-manager/xenia-manager/releases/tag/experimental). Give it a test and let me know if it works properly.

**Comment by NoDowt** [comment]
Just tested & it appears to be working fine now. Thanks.
