### ISSUE TITLE
[Bug] Adding a local patch moves file from current location rather than copying

### ISSUE THREAD

**Issue by NoDowt** [xenia-manager/xenia-manager#164]
## Describe the bug
When adding a game patch from local files, the selected file is moved to the patch folder & deleted from the original location.

## To Reproduce
1. Right Click a game
2. Select Games Patch > Download & Apply Patch
3. Click yes when prompted for locally downloaded 
4. Browse to patch file & open
5. Check location patch file was originally saved & see it is gone

## Expected behavior
That the patch file is copied to the Patches folder & original file is left unmodified in original location.

## Environment Information

- OS: Windows 11
- App Version: 1.15.0

**Comment by shazzaam7** [comment]
Actually, this is what I intended, but I'm happy to change this so it doesn't delete the original file.

**Comment by NoDowt** [comment]
I think it makes more sense to leave the original file where it is; or perhaps make it a checkbox for what behavior the user wants.

When you add additional patches, it leaves the original file as is & just adds it content to the patch file already in the Patches folder. The difference in behavior of 1st patch & additional patches was what originally caught my eye (i.e. why was one of my file missing)

**Comment by shazzaam7** [comment]
I've changed this in the [dev build](https://github.com/xenia-manager/xenia-manager/releases/tag/experimental) so it only copies the file. Give it a test and let me know if it works properly.

**Comment by NoDowt** [comment]
Thanks. Just gave it a test & working fine. Leaving the original files in place.
