### ISSUE TITLE
[Feature Request] Option to 1. Resize Window and 2. Adjust Font Size

### ISSUE THREAD

**Issue by shibenb** [xenia-manager/xenia-manager#172]
Problem:
1. Window size is fixed with a row size of 5 boxarts and column size somewhere between 2 and 3. The non-integer column size creates improper aesthetics. The fixed window size also gives no option to have custom row and column boxart count.
2. Buttons and fonts are too large

Possible Solution:
1. Allow window size adjustments so that I can have custom count of rows and columns of boxarts. Preferable if the window size is remembered across sessions
2. Allow global font and button scaling options (e.g. 0.5 to scale all sizes by half)

**Comment by shazzaam7** [comment]
I will be honest, my UI skills aren't the greatest, hence why I made it that specific size with no ability to resize (although I might change that it in the future).

**Comment by shibenb** [comment]
I wrote a comment and then I think I didn't submit it. I am not a coder but I think I should be able to help if you are ok with that. The font and icon scaling should be possible in the form xml files or if you have hardcoded, I will just need a little help locating those parts in the code. Window being resizable should be a flag that you need to keep on while creating the window.

Let me know what you think

**Comment by shazzaam7** [comment]
Oh no, I meant in a way where I'm not really creative, but I can replicate things.

**Comment by shibenb** [comment]
Hehe, alright! But I didn't mean if you don't know the area, I meant if you don't have time and need a hand. Anyway, looking forward to more releases! You have no idea how many have waited so long for this. We only had a youtube video to hold on to, hehe. Absolutely loving it!
