### ISSUE TITLE
[Bug] The launch failed 

### ISSUE THREAD

**Issue by IamGibs** [xenia-manager/xenia-manager#183]
Hello to whomever receive this email I’m reaching out for a problem I’ve encountered all my roms are my own and I’m using Xenia manager for my rooms for some odd reason I tried to load up my roms in Xenia manager and I get a message that says “ failed to launch title path is invalid. Provided path: E:\Spider-man webs of shadows USA” it will not let load up my roms at the moment so I’m reaching out to you to see if maybe if this is a common problem I have an experience the title not launching before so I would appreciate it if I can get some help with this maybe at some point?
![image](https://github.com/user-attachments/assets/dccb3c15-74ad-46a5-bcc0-4e0e3f03a861)

https://github.com/user-attachments/assets/226947be-910a-4acc-9950-1d1a9bdd2a40

**Comment by shazzaam7** [comment]
Did you move your games to a new folder?

**Comment by IamGibs** [comment]
> Did you move your games to a new folder?

I did not if anything I just added spider-man web of shadows to my current folder

**Comment by shazzaam7** [comment]
Can you confirm the game is in the provided path?
