### ISSUE TITLE
[Bug] Downloading Xenia Canary through Xenia Manager triggers virus warning from Microsoft Defender

### ISSUE THREAD

**Issue by PrinceOfIonia** [xenia-manager/xenia-manager#184]
## Describe the bug
Exactly as title says. 

## To Reproduce
1. Download Version 1.15.2 of Xenia Manager
2. When first opened, select to install Xenia Canary
3. Microsoft Defender triggers virus warning around the 66% mark on the progress bar
4. Xenia Manager then says "Xenia not found" when trying to access Xenia Settings

## Expected behavior
There should have been no virus warning and that Xenia settings should have worked.

## Screenshots/Video
![Screensho4123t_1](https://github.com/user-attachments/assets/b0119b80-1d5d-479f-98d0-d3ab3d096587)
Here is the Microsoft Defender details.

## Environment Information
- OS: Windows 10
- App Version: Version 1.15.2

## Log File
- Xenia Manager Log: https://pastebin.com/3C0iS9hA

## Additional context
Downloading the Xenia Stable version did not cause any of these issues as far as I can tell. I was able to go into Xenia Settings after I downloaded the Stable version, and I got no virus warning.

**Comment by shazzaam7** [comment]
This happens from time to time with Xenia Canary updates because Windows Defender decides to flag it. Nothing I can do about it sadly.
