### ISSUE TITLE
[Bug] Xenia Canary not installing DLC or title updates

### ISSUE THREAD

**Issue by SnowEstheim** [xenia-manager/xenia-manager#185]
## Describe the bug
When right clicking the game and clicking on content>install content, you are able to browse where the DLC or title update is, once you install the content you want a confirmation box appears saying it has successfully installed the content, however when viewing the downloadable content folder there is no content installed for DLC's and in the installer folder there is no title update being installed either.

## To Reproduce
1. Right click a game
2. Go to 'content>'
3. Select 'install DLC/Updates'
4. Browse for your DLC/Update
5. Confirm installation.
6. Go back to step 1
7. Go to 'content> view installed content'
8. Drop down box to 'Downloadable Content' or 'Installer'
9. No content installed.

## Expected behavior
Expected behavior is to have the DLC or Title update appear within their respective folders however it does not occur.

## Screenshots/Video

![Screenshot 2024-10-29 115614](https://github.com/user-attachments/assets/fde27f96-695c-49be-9ddf-bdd40b861dc2)
As you can see above I am in the Downloadable Content folder of Gears of War 3 and I have installed a booster DLC pack and have received a confirmation that the installation was successful however the folder is still empty.

## Environment Information
- OS: Windows 11
- Xenia Canary lastest build as of 29 October 12AM

## Log File
- Xenia-vfs-dump.log [https://pastebin.com/3jbA5TGB]

**Comment by shazzaam7** [comment]
The reason is because you haven't migrated  to the new "profiles" system that was introduced in one of the newer versions of Xenia Canary.

**Comment by SnowEstheim** [comment]
I have a profile added and the dlc's load, its just installing new ones dont work through the manager, I added them manually and it was there

**Comment by shazzaam7** [comment]
Can you post Xenia Manager logs?

**Comment by shazzaam7** [comment]
There should be a Logs folder with Xenia Manager logs.

**Comment by SnowEstheim** [comment]
[Log-20241029.txt](https://github.com/user-attachments/files/17555665/Log-20241029.txt)

**Comment by shazzaam7** [comment]
Could you do a fresh installation of Xenia Manager and try to install content? You don't have to delete your current one.

**Comment by SnowEstheim** [comment]
Okay so I did a fresh install on a different drive and I firstly installed canary and went to create a new profile. I added gears 3 and I have locally downloaded a title update, I added it and the dlc, I see now that in the contents folder (where I only had the created profile) it created another profile and thats why the content does not show up in the view installed content section.

**Comment by SnowEstheim** [comment]
Maybe you could let us choose the directories and for those that dont want to it can auto choose the default ones

**Comment by shazzaam7** [comment]
I did this just as maintenance since I'm mostly focusing on v2 of Xenia Manager so if people don't like v2, they can continue using v1
