### ISSUE TITLE
[Feature Request] Update Xenia versions

### ISSUE THREAD

**Issue by ghenry22** [xenia-manager/xenia-manager#193]
## Is your feature request related to a problem? Please describe.
No

## Describe the solution you'd like
An option to check for updates to the various Xenia forks and to download and install those updates would be excellent for keeping things well managed.

## Describe alternatives you've considered
Check github, download, update manually outside of the manager.

## Additional context
Currently you can install or uninstall xenia versions but there doesn't seem to be any mechanism to update

**Comment by shazzaam7** [comment]
It auto checks for updates every day.
