### ISSUE TITLE
[Help] Does Xenia Manager support xbla games?

### ISSUE THREAD

**Issue by Saigaiii** [xenia-manager/xenia-manager#197]
If so, how do I go about adding them? Because I’m trying to add the goldeneye remake xbla file and it doesn’t come up in the Xenia window pop up, just stays black and then the manager tells me the title couldn’t be found. I’m assuming I’m doing something wrong, just don’t know what exactly.

**Comment by shazzaam7** [comment]
No, it's just the manager couldn't find the game in it's database. Just let it add it using default artwork.
