### ISSUE TITLE
[Bug] GoldenEye menu sensitivity setting doesn't save

### ISSUE THREAD

**Issue by ElTioRata** [xenia-manager/xenia-manager#204]
## Describe the bug
Any adjustment to the mouse sensitivity values on GoldenEye's main menu isn't saved and the setting remains at its default value.

## To Reproduce
1. Install GoldenEye on Xenia Manager and assign it to Xenia Mousehook
2. Go to Settings and modify the menu sensitivity value
3. Save changes
4. Don't feel any difference

## Expected behavior
Menu mouse sensitivity changes.

## Environment Information

- OS: Windows 10
- App Version: 2.0.0

**Comment by shazzaam7** [comment]
Looks like that setting has been removed from the configuration file (At least in mine), hence why changing it doesn't do anything. Can you check in your configuration file if there's an option `ge_menu_sensitivity`.
I'll need to remove it in the next update.

**Comment by Clippy95** [comment]
> Looks like that setting has been removed from the configuration file (At least in mine), hence why changing it doesn't do anything. Can you check in your configuration file if there's an option `ge_menu_sensitivity`. I'll need to remove it in the next update.

I changed it to menu_sensitivity as it effects Saints Row 1 now too

**Comment by ElTioRata** [comment]
> Can you check in your configuration file if there's an option `ge_menu_sensitivity`. I'll need to remove it in the next update.
I only have "menu_sensitivity = 0.5".

**Comment by shazzaam7** [comment]
This has been fixed in [Experimental Build ab1064d](https://github.com/xenia-manager/xenia-manager/releases/tag/ab1064d).

**Comment by shazzaam7** [comment]
Fixed in [v2.1.0](https://github.com/xenia-manager/xenia-manager/releases/tag/2.1.0)
