### ISSUE TITLE
[Bug] Unable to find default config

### ISSUE THREAD

**Issue by brugalman** [xenia-manager/xenia-manager#205]
## Describe the bug
I installed Xenia Manager 2.0.0 today and couldn't find any way to adjust the default configuration.

## To Reproduce
1. Go to Settings
2. Click on game list
3. See error

## Expected behavior
A way to configure the default settings so I don't have to do it for every single game.

## Environment Information
- OS: Windows 11
- App Version: 2.0.0

**Comment by shazzaam7** [comment]
This is because of how `per game configuration` works now. Every configuration file is the "default" one because it's loaded up that way.

**Comment by brugalman** [comment]
Ohhh okay. Thanks for the response though!
