### ISSUE TITLE
[Bug] Cannot create profile

### ISSUE THREAD

**Issue by naddel91** [xenia-manager/xenia-manager#213]
When launched via Manager Xenia cannot create/load a profile. Therefore I cannot start Banjo-Tooie.

When launched without manager, it works fine.

**Comment by shazzaam7** [comment]
Can you provide me your log files (They're in the Logs folder). Upload them on [pastebin](https://pastebin.com/) or a similar site.

**Comment by naddel91** [comment]
[Log-20241226.txt](https://github.com/user-attachments/files/18270861/Log-20241226.txt)
[Log-20241229.txt](https://github.com/user-attachments/files/18270862/Log-20241229.txt)

**Comment by shazzaam7** [comment]
That has nothing to do with profiles. Go into the `Profiles`, `Show Profile Menu` and check if you logged into your profile.
The only issue I see is not saving the profiles that have been logged into because symbolic link failed.

**Comment by naddel91** [comment]
tried to reproduce. when the same game is started using xenia manager, I cannot log into profile, nor can I create one. 
when just started via xenia-canary.exe everything is fine.

**Comment by shazzaam7** [comment]
Can you do a video of this?

**Comment by naddel91** [comment]
We don’t support that file type.

Where to upload?

**Comment by shazzaam7** [comment]
[GoFile](https://gofile.io/)

**Comment by naddel91** [comment]
https://gofile.io/d/sw8DZL

https://gofile.io/d/q1mWPd

**Comment by shazzaam7** [comment]
Okay, I see that you "updated" from v1 to v2 of the Manager. Those 2 versions are incompatible with each other. Can you try a fresh install in a separate folder?

**Comment by naddel91** [comment]
seems to do the trick. something went wrong during the update, I guess. 
One thing I noticed is VSync is not completely implemented, I guess. It has tearing every now and then although I have vsync ON,

**Comment by shazzaam7** [comment]
That might be Xenia's issue.

**Comment by naddel91** [comment]
works fine now. manager should come bundled with xenia to begin with!
