### ISSUE TITLE
Can't scroll games page

### ISSUE THREAD

**Issue by SmokeyMcGames** [xenia-manager/xenia-manager#41]
I've added around 41 games to the mananger and noticed I can't scroll down through the games to see the others.

I also was wondering if the ability to change game names and images would be possible in the future?

Also wondering if adding multiple disc games was going to be added as well at some point.

**Comment by shazzaam7** [comment]
I'll add the scrolling ability, but I don't have that many games to test it properly.

As for the multi disk part, I'll add it when I add the ability to edit game info (Name, Location to the game, etc.)

**Comment by shazzaam7** [comment]
Hi, can you test out the fix in the [experimental branch](https://github.com/xenia-manager/xenia-manager/releases/tag/experimental) and let me know if the scrolling is fixed?

**Comment by SmokeyMcGames** [comment]
The fix you provided seems to have fixed the scrolling issue in the games section.

**Comment by shazzaam7** [comment]
Thanks for the fast reply, I'll close this issue and open another one for your feature request.

Fixed in 5736d8f
