### ISSUE TITLE
Add language selection

### ISSUE THREAD

**Issue by Etervilan** [xenia-manager/xenia-manager#43]
I would like to be able to change user_language in the GUI.
For example in Gears of War 2 this parameter changes the language in the game.

**Comment by shazzaam7** [comment]
Added in dd3258b

Also it's now in the latest [experimental release](https://github.com/xenia-manager/xenia-manager/releases/tag/experimental). Could you give it a go before I close this issue?

**Comment by Etervilan** [comment]
I have tested it, it works fine. Thanks

**Comment by shazzaam7** [comment]
Thanks for testing, closing this issue. Will be officially added in a new version. For now you can use the experimental version.
