### ISSUE TITLE
Xenia Manager not running Arkham Origins config file

### ISSUE THREAD

**Issue by markjfine** [xenia-manager/xenia-manager#48]
Installed Batman Arkham Origins to Xenia Manager (XM), adding `launch_module = "SP.xex"` to the config file. XM sees and runs the applicable title updates, but does not use the custom config file. The game won't run from default.xex and must be run from SP.xex, therefore the launch fails.

1. Run `C:\Xenia\xenia_canary.exe <game path>\Content\0000000000000000\57520828\00004000\56B7A4470DB037981526DFD01E1F12E7 --launch_module="SP.xex"` to show it works from the command line.
![Game screen capture](https://github.com/user-attachments/assets/9f7d5196-87ba-4cee-915e-d9932fbd746d)

2. Edit `C:\Xenia\config\Batman™ Arkham Origins.config.toml` to include `launch_module = "SP.xex"`. (removed TM for purposes of zip file)
[Batman™ Arkham Origins config file](https://github.com/user-attachments/files/16326668/Batman.Arkham.Origins.config.zip)

3. Click on game icon in Xenia Manager.
![Xenia Manager w/Arkham Origins](https://github.com/user-attachments/assets/67a17d05-0924-491a-a4f6-381faffe4695)
[Xenia Manager log showing game launch was attempted](https://github.com/user-attachments/files/16326711/XM_log.zip)

4.  Game fails.
![Resulting error](https://github.com/user-attachments/assets/5d655947-eb92-49c0-9d6a-7f00b201bc8c)
[Canary log showing config file wasn't used running from default.xex](https://github.com/user-attachments/files/16326689/XC_log.zip)

Expectations:
I expected the game to use the config file and launch it using `SP.xex`, similar to step 1 above, but from the logs it's evident it was launching `default.xex` instead. Unsure how else to get the game to run within Xenia Manager.

Other Observations:
This is not the only title that contains a title update and launch_module specification (e.g., Assassin's Creed IV), though it is the only such game that was ripped from disk. Initial install into Xenia Manager of Arkham Origins had a similar problem until I tricked it to launch `SP.xex` using the default config file during the install.

Screen captures and logs embedded within.

**Comment by shazzaam7** [comment]
Just to be sure, can you increase draw resolution to 2 or 3 and then launch the game? Does it say in the title of Xenia window 2x2 or something similar?

**Comment by kingof2520s** [comment]
@markjfine unrelated to the initial issue but i had a question, how exactly do you have all the pictures loading just fine? Many of my games only allow a blank disc image to be the icon for some reason.

**Comment by markjfine** [comment]
@shazzaam7
> Just to be sure, can you increase draw resolution to 2 or 3 and then launch the game? Does it say in the title of Xenia window 2x2 or something similar?

Chicken and egg issue here. I can set in the default configuration and it still fails, because it's not launching from the custom config telling it to launch `SP.xex`. I mean, I can set it to launch properly from the default config too, but then all of the other games will fail,  defeating the whole purpose of the per-game custom configs.

> Also, I assume the game is a 2 disc game, correct?

Basically a 2-disk game, but XBox won't install the second disk. It's basically for multiplayer online, almost another game completely.

**Comment by markjfine** [comment]
> @markjfine unrelated to the initial issue but i had a question, how exactly do you have all the pictures loading just fine? Many of my games only allow a blank disc image to be the icon for some reason.

I did it manually. Found a good image to use either from XBox marketplace or something else, 'saved as' with the game name XM uses and an .ico extension, then moved it on top of the one in the Icons directory. In fact, sometimes the one found on Wikipedia or the other list are meh, so I replace it to make it look better.

**Comment by shazzaam7** [comment]
Okay so here's what I gathered from my research so far.

The configuration file loads, but for some reason `launch_module` isn't (My guess is that it's one of those settings that is initialized before per-game configuration loads ([Reference to what I'm talking about](https://github.com/xenia-canary/xenia-canary/wiki/Options#how-to-use)).

I also noticed your game is in 'Installed Game' format (00004000), so what you can do is extract it (Think Xenia VFS Dump Tool will work just fine) and in the extracted folder you will see 2 files (default.xex & SP.xex). You add SP.xex as the game and it will work just fine. I know this is a bypass and I'm sorry for that.

What I can do is add a detection to stuff like this so it can warn the user or even use the Xenia VFS Dump tool (since it's downloaded on first setup) to extract the game into the 'installed' format and then add the game that way.

If you have any further questions let me know.

**Comment by markjfine** [comment]
Strange, but for '4' types (installed from disk) you could be right. I did have a problem adding the game to XM at first. Let me expand the game file and see if this works.

**Comment by markjfine** [comment]
Interesting: Dumped the install file and edited installedGames.json to point to SP.xex... it worked. In fact, I think it's now using the title update that fixes the famous 'infinite fall' problem in NG+.

Also didn't realize that VFS Dump completely uncompresses the whole game, to include everything in the .dat directory. There was even a $SystemUpdate with a completely updated dash in there... wild stuff.

I may do this for all the '4' types, just to make sure those are reading the TUs as well.

**Comment by markjfine** [comment]
Somewhat related, but as an FYI:
In VFS-dumping the other `installed from disk` games, I noticed that Xenia has a confusion problem with a registered symbol in the config file's name... I just edited them out of installedGames.json as well as the filenames in the config directory, and Xenia is happy again. May want to include a check for this when doing a game add.

**Comment by shazzaam7** [comment]
Thank you for the FYI. I have fixed it in the 12567c7.
