### ISSUE TITLE
Having issue adding Split\Second cuz of \ symbol

### ISSUE THREAD

**Issue by metalslayer** [xenia-manager/xenia-manager#51]
![splisecond](https://github.com/user-attachments/assets/6c54c2e9-e083-4411-b761-d20e9f4af291)

**Comment by shazzaam7** [comment]
Can you try the fix in the [experimental version](https://github.com/xenia-manager/xenia-manager/releases/tag/experimental) (Just back up your current xenia manager executable and copy and paste the experimental one, make sure you re add the game).

**Comment by shazzaam7** [comment]
Fixed in [bb1590e](https://github.com/xenia-manager/xenia-manager/commit/bb1590ec674f6c61e47897ecab85a01c5713f6d0)
