### ISSUE TITLE
game starts instantly

### ISSUE THREAD

**Issue by artem45ik** [xenia-manager/xenia-manager#55]
When I select .xex file emulator starts

https://github.com/user-attachments/assets/1b17b72e-a6e9-4077-991d-05510a0e3483

and if i close emulator this appear
![Снимок экрана (516)](https://github.com/user-attachments/assets/421a560d-4bc8-4f6c-a50a-90e8465be3c4)

**Comment by shazzaam7** [comment]
Can you post the Xenia Manager log file?

**Comment by artem45ik** [comment]
idk if this is right log 
[Log-20240728.txt](https://github.com/user-attachments/files/16404162/Log-20240728.txt)

**Comment by shazzaam7** [comment]
Yes it is. Does this only happen with other games?

**Comment by artem45ik** [comment]
i haven't tested other games only Forza Motorsport 2

**Comment by shazzaam7** [comment]
I see now. When you try to add the game, for some reason Forza Motorsport 2 title doesn't appear in the Xenia Window Title, meaning the Manager can't detect the game properly and it's waiting for it to appear. I have made it to stop after 100 tries (every 100 milliseconds it will try again). Leave it to run it's course and it will automatically close the emulator.

**Comment by artem45ik** [comment]
okay gonna try

**Comment by artem45ik** [comment]
now its says this 
![Снимок экрана (517)](https://github.com/user-attachments/assets/cc98fe04-3385-4249-973b-2433050b85b0)

**Comment by shazzaam7** [comment]
Now in the textbox where it says "Not found" type your game's name and select it from the list. (You can switch lists of games by pressing on the combobox where it says "Xbox Marketplace", although that one should be the best in my opinion).

**Comment by shazzaam7** [comment]
Everything working now?

**Comment by artem45ik** [comment]
Yea

https://github.com/user-attachments/assets/d61c92f0-160c-472c-b2ed-fc8dcba10745
