### ISSUE TITLE
Game Crash Forza Motorsport 2

### ISSUE THREAD

**Issue by artem45ik** [xenia-manager/xenia-manager#57]
game crashes after 1 lap and only solution using xenia canary build from 5 October 2022 50fce8b
![Снимок экрана (521)](https://github.com/user-attachments/assets/b524662a-90c2-4848-99e3-c803e3d8063a)

**Comment by shazzaam7** [comment]
> game crashes after 1 lap and only solution using xenia canary build from 22 October 2022

This looks more like a question for Xenia Team.

**Comment by artem45ik** [comment]
> > game crashes after 1 lap and only solution using xenia canary build from 22 October 2022
> 
> This looks more like a question for Xenia Team. Not sure what my response should be considering you're using an old build of Xenia (Probably not installed using Xenia Manager).

i'm using newer build

**Comment by artem45ik** [comment]
for forza games needed build 50fce8b or 5 october 2022

**Comment by shazzaam7** [comment]
Really don't understand what this has to do with Xenia Manager. From my POV you're using an old build for this game and you got an error. Xenia Manager would install [eeb96f91a](https://github.com/xenia-canary/xenia-canary/releases/tag/eeb96f9) build.

**Comment by artem45ik** [comment]
> Really don't understand what this has to do with Xenia Manager. From my POV you're using an old build for this game and you got an error. Xenia Manager would install [eeb96f91a](https://github.com/xenia-canary/xenia-canary/releases/tag/eeb96f9) build.
i used that build and everything seems fine until i tried race when i got crash and later i tried again and again crash but before using xenia manager i played on this [50fce8b](https://github.com/xenia-canary/xenia-canary/releases/tag/50fce8b) and no crashes

**Comment by shazzaam7** [comment]
Now I understand you, but this has nothing to do with Xenia Manager. It installed the latest Xenia Canary version and it launched the game.

**Comment by artem45ik** [comment]
> Now I understand you, but this has nothing to do with Xenia Manager. It installed the latest Xenia Canary version and it launched the game. If you have an issue with Xenia Manager, this is the place to submit issues.

now I think I need to be able to choose the build I need for the game

**Comment by shazzaam7** [comment]
I'll add it on my TODO list, but don't expect it any time soon.

**Comment by artem45ik** [comment]
> I'll add it on my TODO list, but don't expect it any time soon.

okay i will wait
