### ISSUE TITLE
Add scrollbar to the interface

### ISSUE THREAD

**Issue by bartvincke** [xenia-manager/xenia-manager#58]
Please add a scrollbar to the interface. currently the interface is barely useable on all device without a real mouse attached, including touch screen devices and handheld gaming devices.

**Describe the solution you'd like**
A scrollbar to move through the gui by clicking into it

**Comment by shazzaam7** [comment]
I'm currently working on support for Xenia Netplay, but when I'm done I'll add some scroll bars. In the future I want to add a "Big Picture" mode similar to the Steam one.

**Comment by shazzaam7** [comment]
![EYoMg1Kqrk](https://github.com/user-attachments/assets/70d0df88-4691-4dd8-9f7d-f362c2daa309)

Is something like this what you had in mind?

**Comment by shazzaam7** [comment]
Thanks for the reply. Expect it in the next release (1.9.0) and if something changes I'll post an update here.
