### ISSUE TITLE
suggestion: add per game config option

### ISSUE THREAD

**Issue by bartvincke** [xenia-manager/xenia-manager#59]
**Is your feature request related to a problem? Please describe.**
Some games ( all DOA games for example ) require changes to the xenia config file which would negatively impact other games if set permanently in the default config file.

**Describe the solution you'd like**
Depending on how xenia manager accesses xenia this could be done in 2 ways:
either add an option to just create a custom config ( copy of the default config.toml file ) under config/titleid.config.toml or if the way xenia is accessed is through cli, ceate the file but also add --config titleid.config.toml to the parameters ( + path )

**Additional context**
Per game config would simplify settings a lot

**Comment by shazzaam7** [comment]
This is already implemented. In Xenia Settings, "Default Profile" is only used to create new config files for every new game, nothing else. You can click on it and change to whatever game you want to change something.

**Comment by artem45ik** [comment]
> This is already implemented. In Xenia Settings, "Default Profile" is only used to create new config files for every new game, nothing else. You can click on it and change to whatever game you want to change something.

regarding different versions of xenia, can you implement this as it was with the config when each game has its own config file

**Comment by shazzaam7** [comment]
> regarding different versions of xenia, you can implement this as it was with the config when each game has its own config file

Don't think I understand what you meant.

**Comment by artem45ik** [comment]
> > regarding different versions of xenia, you can implement this as it was with the config when each game has its own config file
> 
> Don't think I understand what you meant.

you have game settings for each game you can also make each game have its own version of the emulator

**Comment by shazzaam7** [comment]
I understand, but the whole point of this program is to keep everything up to date.

**Comment by bartvincke** [comment]
Thank you for the feedback, I confirm the configs get created.
I missed that

The topic can be closed as it's already implemented

**Comment by artem45ik** [comment]
> I understand, but the whole point of this program is to keep everything up to date.

some games on xenia canary needs different build
