### ISSUE TITLE
Internal Resolution setting doesn't seem to do anything

### ISSUE THREAD

**Issue by wigwoo1** [xenia-manager/xenia-manager#60]
**Describe the bug**
no matter what the internal Display resolution setting is set to, the emulator seems to always default to 720p and won't scale. I also noticed it only goes up to 1920x1080 and wasn't sure how to set it to 1440p or 4K

**Expected behavior**
I would expect the resolution of the game to be rendered at whatever setting I chose

**Screenshots**
![Untitled-11](https://github.com/user-attachments/assets/577e84ba-0fc7-4054-86b1-5fac78b471d9)

**Log File**

[xenia.log](https://github.com/user-attachments/files/16417036/xenia.log)

**Comment by shazzaam7** [comment]
Game has to support internal resolution for it to work. Xbox 360 supports only resolutions listed in the ComboBox ([source](https://github.com/xenia-canary/xenia-canary/wiki/Options#internal-display-resolution)). If you want to increase the game resolution, look at increasing "Draw Resolution Scale".

**Comment by wigwoo1** [comment]
![Untitled-1](https://github.com/user-attachments/assets/528eb9b6-929e-4767-b523-deb25a434bc4)

I can also confirm changing the Draw scale doesn't appear to change the resolution in any way either

**Comment by shazzaam7** [comment]
Are you changing the game configuration file or the "Default Profile"?

**Comment by wigwoo1** [comment]
The default profile as I assume that changes "every" game to match right?

**Comment by shazzaam7** [comment]
No, "Default Profile" is only used for creating other profiles.

**Comment by wigwoo1** [comment]
Ahh ok. That seemed to work. Though game is heavily flickering but that's probably just a Compatibility issue not related. Thank you
