### ISSUE TITLE
[Feature request] Add option to select/import existing xenia installations into Xenia Manager

### ISSUE THREAD

**Issue by dyno0** [xenia-manager/xenia-manager#65]
Long time users may have multiple xenia fs locations or portable fs locations with different dlcs, game updates and patches applied, so it would be convenient if these could just be imported as existing installations instead of forcing the user to install the fresh installation.

**Comment by shazzaam7** [comment]
Right now you can install Xenia (Stable, Canary or Netplay build) and just copy and paste your already installed Xenia version (provided that they are in portable mode) to the location where Xenia Manager installs it's own (I made it install Xenia versions next to it's executable so it's as portable as possible) and they should work out of the box.

I'm still unsure if I want to support multiple versions of the Xenia because the whole point of Xenia Manager is to keep the Xenia versions up to date.

**Comment by ArtemGT69** [comment]
> Long time users may have multiple xenia fs locations or portable fs locations with different dlcs, game updates and patches applied, so it would be convenient if these could just be imported as existing installations instead of forcing the user to install the fresh installation.

I'm have older xenia canary just because Forza Motorsport 2 crashes after 1 lap on newer version of xenia

**Comment by ArtemGT69** [comment]
just didn't understand what that means
![Снимок экрана (540)](https://github.com/user-attachments/assets/04e12c65-227d-479e-b854-e7239922bb06)

**Comment by shazzaam7** [comment]
I have added an option to Switch to a Custom Version of Xenia in #84 and merged it into the dev branch.
You can test this in the new [experimental build](https://github.com/xenia-manager/xenia-manager/releases/tag/experimental) and let me know if this fits your needs in having another version of Xenia.

**Comment by dyno0** [comment]
Per game choice is good, but it's still left with an overhead of force installing clean xenia installs, most likely left unused, just to make use of this feature.

> ...
> I'm still unsure if I want to support multiple versions of the Xenia because the whole point of Xenia Manager is to keep the Xenia versions up to date, but importing already installed Xenia versions (if they are portable) is something I can make it happen and then keeping those up to date.

I was more aiming towards this on the import part, along with the management of multiple xenia install versions.
I'll keep the issue open if you want to track the future topics of this feature, or you can close it at your convenience.

**Comment by shazzaam7** [comment]
Ah so you want an option to just straight import existing Xenia into Xenia Manager?

**Comment by dyno0** [comment]
Basically yea, for starters maybe allow importing one of each xenia installataions, and then eventually importing and managing multiple build commit versions for each xenia installation.

**Comment by shazzaam7** [comment]
I can allow for importing content, but I don't like managing multiple build commit versions because the whole purpose, like I said, is to keep Xenia stuff up to date. This is where the "Switch to Custom Xenia" comes in if you want to a specific version of Xenia for a game.

**Comment by dyno0** [comment]
Ah ok, from that standpoint it's true, I thought it'd be more convenient to have the user import multiple build commit versions and themselves managing them to their liking (along with the option to update to latest) with the convenience of dlc, title updates and game patches management for each install than having a single instance which can run a game with a custom install but can't share customized dlc, title updates and game patches settings.

**Comment by jkadaks** [comment]
Also the benefit of this feature is to keep latest xenia and xenia-canary executables in the same folder which currently Xenia Manager does not allow an option for.
I’m sure I’m not the only user who does that with both xenia versions - this allows them both sharing games saves, game patches and any installed game updates and content. They already have different config files names so there is no conflict there. I think this would be great feature to have for long time xenia users with this setup. Really hope it’s manageable!

**Comment by shazzaam7** [comment]
> Also the benefit of this feature is to keep latest xenia and xenia-canary executables in the same folder which currently Xenia Manager does not allow an option for. I’m sure I’m not the only user who has both xenia versions in the same folder - this allows them both sharing games saves, game patches and any installed game updates and content. They already have different config files names so there is no conflict there. I think this would be great feature to have for long time xenia users with this setup. Really hope it’s manageable!

The problem with that is some issue may occur when Xenia Canary gets a new feature that doesn't work well with Xenia, hence why I separated them into their own directories. (Example: Xenia Canary gets support for saving achievements that causes Xenia Stable to suddenly have issues with save files). This isn't difficult to implement, but I see too many complications that can happen where I don't think this is a valid enough feature.

**Comment by jkadaks** [comment]
> feature.



> > Also the benefit of this feature is to keep latest xenia and xenia-canary executables in the same folder which currently Xenia Manager does not allow an option for. I’m sure I’m not the only user who has both xenia versions in the same folder - this allows them both sharing games saves, game patches and any installed game updates and content. They already have different config files names so there is no conflict there. I think this would be great feature to have for long time xenia users with this setup. Really hope it’s manageable!
> 
> The problem with that is some issue may occur when Xenia Canary gets a new feature that doesn't work well with Xenia, hence why I separated them into their own directories. (Example: Xenia Canary gets support for saving achievements that causes Xenia Stable to suddenly have issues with save files). This isn't difficult to implement, but I see too many complications that can happen where I don't think this is a valid enough feature.

I see your point, that’s a valid case, and from development standpoint might be tricky to manage. With that in mind, it could be more of an experimental kind of feature with “there might be dragons” warning for those who want to go that route.
