### ISSUE TITLE
Support for .zar

### ISSUE THREAD

**Issue by carlosgamer23** [xenia-manager/xenia-manager#69]
Xenia currently supports .zar

Make a Manager for Xemu too, that's a great job

**Comment by shazzaam7** [comment]
Please keep this repository strictly about Xenia features.

**Comment by carlosgamer23** [comment]
It would be good for Xemu to have box arts, and individual settings for each game, I already spoke to the Xemu dev, he said that formats for compression are in the plans but it will be the last thing he does

**Comment by carlosgamer23** [comment]
Ok, I hope support for .zar in your next update, and thanks for all your hard work.

**Comment by carlosgamer23** [comment]
> Por favor, mantenha este repositório estritamente sobre os recursos do Xenia.

Ok, I hope support for .zar in your next update, and thanks for all your hard work.
