### ISSUE TITLE
Add "All possible licenses" option in Xenia settings

### ISSUE THREAD

**Issue by b9natwo** [xenia-manager/xenia-manager#72]
Add an "All possible licenses" option for license mask.

**Comment by shazzaam7** [comment]
From my knowledge, `First License` (AKA `license_mask=1`) works perfectly fine.
Why do you want the `-1` option. I've asked around and people generally don't recommend it unless it's absolutely necessary and `First License` does the job. Also Xenia Wiki says you can use **EITHER** `First License` (AKA `license_mask=1`) or  `All Licenses` (AKA `license_mask=-1`)

**Comment by shazzaam7** [comment]
After talking to people on Xenia's Discord server, turns out this is used in really rare cases such as Modern Warfare 3 DLC's only being loaded with `license_mask=1`. Added in #73 onto dev branch and coming in version 1.10.0.

**Comment by b9natwo** [comment]
> From my knowledge, `First License` (AKA `license_mask=1`) works perfectly fine. Why do you want the `-1` option. I've asked around and people generally don't recommend it unless it's absolutely necessary and `First License` does the job. Also Xenia Wiki says you can use **EITHER** `First License` (AKA `license_mask=1`) or `All Licenses` (AKA `license_mask=-1`)

Just responding. thank you for the update. while i was playing Real Steel, my game would be set to the trial version when on the first license. After changing it to -1 it unlocked the full game and gave me the dlcs. I had to keep going from Xenia Manager to my text editor to switch it.
