### ISSUE TITLE
Feature Request: Download and Install title updates within UI using XboxUnity (Something similar to adding patches)

### ISSUE THREAD

**Issue by CuddleBear92** [xenia-manager/xenia-manager#77]
**Is your feature request related to a problem? Please describe.**
No easy way to download title updates within the UI, needing to manually hunt for them yourself.

**Describe the solution you'd like**
I would like for the manager/UI to be able to search up the title ID on <http://xboxunity.net/> and download the update files and install with simple options. One click to install it to the newest version, maybe a dropdown to select the version you want to have installed.

**Describe alternatives you've considered**
archive.org lookup might work too but that would requires more hands on work by the user.

**Side note:**
That site also host cover art for multiple regions at once with full front and back inlays that might be needed for a 3D view.

**Comment by shazzaam7** [comment]
Interesting idea. 
Looks doable, but for now, I'll need to first reach out the xboxunity devs to see if I'm allowed to scrape their site for updates. What I can do is when adding games I can also add their "Media ID", which is useful when searching for updates on this site.

For now I'll add it onto my [TODO List](https://github.com/orgs/xenia-manager/projects/2/views/1). I'll reply onto this issue with updates.

**Comment by CuddleBear92** [comment]
> Interesting idea. Looks doable, but for now, I'll need to first reach out the xboxunity devs to see if I'm allowed to scrape their site for updates.
So the site has an API key on a per user level! Just have users sign up and input their own API key would make sense here with a rate limiter.

**Comment by shazzaam7** [comment]
That's something I thought of for using Steamgriddb as a source of boxarts.
I have to think about it. Thanks again for the idea. I'll reopen this issue when I start working on it.

**Comment by shazzaam7** [comment]
From what I can see while looking on that site, API Key isn't used at all on the site so it's just a matter of scraping it. 
For now I've implemented reading of MediaID when adding games which should help users choose the Title Update.

I'll keep an eye on this site. If I decide to implement it, I'll go ahead and ask the devs more about it, but for now I'll leave it be.

**Comment by CuddleBear92** [comment]
well atleast the json is easily parseable: 
http://xboxunity.net/Resources/Lib/TitleList.php?page=0&count=10&search=4D5307D2&sort=3&direction=1&category=0&filter=0
http://xboxunity.net/Resources/Lib/TitleUpdateInfo.php?titleid=4D5307D2

Then you can easily grab the download urls by the TitleUpdateID `http://xboxunity.net/Resources/Lib/TitleUpdate.php?tuid=23209`

you already have the TitleIDs in the client so just pulling the titleupdateinfo is the only thing really needed unless you want to pull cover art aswell.

Seems you can do json responses aswell but thats a bit out of my depth. weird they would have an api key but not use it 🤔 
https://www.se7ensins.com/forums/threads/xboxunity-api-reversed.1841610/

**Comment by shazzaam7** [comment]
Yeah, I already know how to parse it. I've just implemented reading of Media ID for games in the latest version.

**Comment by CuddleBear92** [comment]
oh nice! then you can get the specific update file for that specific game release. good to hear there is progress on this!

**Comment by shazzaam7** [comment]
I'm currently finishing easier tasks, and then I'll fully move on to this.

I'll most likely make some changes to the overall Install Content process (Show the window and have an add button alongside this title update searcher just like patch files? We'll see).

**Comment by shazzaam7** [comment]
I have implemented this in the latest [experimental build](https://github.com/xenia-manager/xenia-manager/releases/tag/experimental). Feel free to test it and give me feedback.
