### ISSUE TITLE
[Feature Request] add option to game folder

### ISSUE THREAD

**Issue by Ebrehe** [xenia-manager/xenia-manager#79]
**Is your feature request related to a problem? Please describe.**
Adding games manually is a bit annoying

**Describe the solution you'd like**
When the application starts, it scans the game folder for new ISOs.

**Comment by shazzaam7** [comment]
A folder containing all of the games?

**Comment by shazzaam7** [comment]
Sadly for now this is not possible as the adding process simply REQUIRES some sort of user interaction (Selecting it from the lists of games to use proper box art for example)
