### ISSUE TITLE
feature request: shortcuts to the manager with game path should launch the game.

### ISSUE THREAD

**Issue by CuddleBear92** [xenia-manager/xenia-manager#82]
So currently, the shortcut system launches Xenia itself with an attached --config param and attached path to the game config. While that works great, it can cause some hassle with some of the emulator frontends like launchbox as it would fail to launch these shortcuts directly without manually correcting it on a per-game basis.
So instead of doing `Xenia.exe "full/pathtogame/game.iso" --config "configpath"` or whatever, it would rather just have something like `Xenia Manager.exe "full/pathtogame/game.iso"` then the manager would handle all the interaction with giving xenia the config file. 
This will make it easier for other UI's and front-ends to work with the manager. Note that the Xenia Manager will still be quite useful next to other frontends for its ease of use.

Current workaround for this for atleast launchbox would be to edit each title properties and turn off emulation as its mapped to the shortcuts... else it fails to launch or launches without the config.

**Comment by shazzaam7** [comment]
My biggest issue is that I don't use Launchbox or similar software (Only Steam/Heroic for EGS, things like that) so I can't really know how it works. 
I was planning on adding an argument where you add the game id next to the Xenia Manager and it would launch the game. (Example: `Xenia Manager.exe "315A07D1"` This would launch NBA 2K16).

**Comment by CuddleBear92** [comment]
>argument where you add the game id next to the Xenia Manager and it would launch the game. (Example: `Xenia Manager.exe "315A07D1"` This would launch NBA 2K16).

Could you have it accept the full game path aswell? as thats the default behaviour for these in the end. ID's would not work with these. Im certain quite a few users will use these frontends as they are quite popular. 

So for example: `Xenia Manager.exe "K:\Roms\Microsoft Xbox 360\Gears of War (USA, Europe) (En,Fr,De,Es,It,Zh,Ko)\Gears of War (USA, Europe) (En,Fr,De,Es,It,Zh,Ko).iso"`

**Comment by shazzaam7** [comment]
No, because it needs to know what emulator to use.

And since I save the game ID alongside other useful things in a JSON file and it's easy to find ("Edit game" window or hovering over the game box art) it makes sense to use the ID.

**Comment by CuddleBear92** [comment]
well, you could just have a list to map the ID's to the specific file path. that way you can lookup the ID from the path that way.

**Comment by M1K3Yio** [comment]
I also use LaunchBox as my preferred front end.  I am playing around with this setup I know this isn't ideal for large libraries, but I've only imported a handful to test with.

Within LaunchBox set the emulator to xenia canary from within xenia manager and I am able to launch `GAME.iso` that don't have set with a config without any issues.

For games with a config like XLBA titles I edit the game within LaunchBox and check `Use Custom Command-line Parameters:` and use a custom command `%romfile% --config "SOMEPATH\xenia_manager\Xenia Canary\config\GAME.config.toml"` .  Idealy it would be nice to have this set in the base emulator settings and have it know the proper game title to match on, but I don't think that's constant enough and depends on an individual user setup.

Maybe this will spark some ideas from others on how we could stream line this more.

**Comment by shazzaam7** [comment]
I have implemented this in the latest [experimental build](https://github.com/xenia-manager/xenia-manager/releases/tag/experimental).
How it works is pretty simple. You add the game in the Xenia Manager and then create a shortcut or whatever and in the launch arguments/parameters you just add the game title (It must be the same as the one found in Xenia Manager, you can open the "Edit Game" window and copy and paste it). Example: `Xenia Manager.exe "Red Dead Redemption"`. If you add multiple games, then it will only launch the first game in the list of arguments and ignore the rest.

Feel free to test it and let me know if it works.

**Comment by Quickshadoww** [comment]
hm how could this be automated / set up in Launchbox ?

**Comment by shazzaam7** [comment]
> hm how could this be automated / set up in Launchbox ?
> 
> Update: got a possible temporarily solution working for launchbox/bigbox.
> 
> in launchbox, setup the xenia emulator as following:
> 
> 1.point to "xenia manager.exe" as the xenia emulator 2.set default command line parameters: "%title%" 3.enable "remove file extension and folder path"
> 
> additional step needed then:
> 
>     1. rename the Rom File to match the Game Title as described by shazzaam7
> 
> 
> ...though i just tested this with an easy game name like "Blur" so far. but it works and loads the custom config =) thanks

I have tested it with games like Red Dead Redemption and Forza Horizon so I don't see why it shouldn't work. Either way I have other features to work on and this isn't in the final release yet so plenty of time to fix issues.
