### ISSUE TITLE
add a link to the github repo in the client!

### ISSUE THREAD

**Issue by CuddleBear92** [xenia-manager/xenia-manager#85]
The client should have a link to the github and perhaps a short word about reporting issues.

**Comment by shazzaam7** [comment]
Reporting issues is detailed when you press "New issues", but a link to the page is a nice improvement. I'll add it.

**Comment by shazzaam7** [comment]
![Tpb4wh5YVF](https://github.com/user-attachments/assets/b16b0991-f482-422f-9935-defe04c6802e)

Added the button to the main window. Coming in 1.11.0
