### ISSUE TITLE
Accessibility issue with text to speech software

### ISSUE THREAD

**Issue by RealAmethyst** [xenia-manager/xenia-manager#90]
**Describe the bug**

The different buttons inside Xenia manager does not have a proper label, meaning that my text to speech software only says "button" I am fully blind and need to know what object I am clicking on. Only button which has a label is the ad game button.

**To Reproduce**
1. Open Xenia manager
2. start the built in screen reader in windows. (Hold ctrl, windows key and press enter)
3. Use your keyboard and tab around the interfase.
4. The screen reader will say "button" and ad game when you get to that.

**Expected behavior**

The screen reader should speak every button and tel me what it does. Same as it does with ad game. I have no idea if it will speak the config section when or if I get there.

**Screenshots**

**Additional context**

**Log File**
Put log file here

**Comment by shazzaam7** [comment]
I have added text to speech support to all of the UI elements. Hopefully this will help you interact with the UI easier. If there is anything I can do to improve it let me know.

You can test this in the new [experimental build](https://github.com/xenia-manager/xenia-manager/releases/tag/experimental).

**Comment by RealAmethyst** [comment]
Just tested it and now everything works as it should. Thank you so much!
