### ISSUE TITLE
[Feature Request] Ability to change the controls used for Xenia

### ISSUE THREAD

**Issue by LOuroboros** [xenia-manager/xenia-manager#92]
Xenia Manager allows to set the keyboard as the preferred input method to use for Xenia, but it does not allow to actually set up whatever keys you want for the emulator's controls. Thinks like mapping the Xbox's Y button to the Keyboard's W or whatever else.

It would be pretty dope if this program could incorporate something like an interface to change the controls at will, like the average emulator has.

**Comment by shazzaam7** [comment]
I have left that out because I thought most people play the games with a controller. For all of the options you can use the "Open in editor" option to change.
From what I know you can change these settings under [HID.WinKey] section.

**Comment by LOuroboros** [comment]
> I have left that out because I thought most people play the games with a controller. For all of the options you can use the "Open in editor" option to change. From what I know you can change these settings under [HID.WinKey] section.

But that just opens the .toml file, and the only way to configure the controls there is to either google up or magically know all the codes for each key.

The entire point of this suggestion was to make it easier for the people using this launcher to configure keyboard controls to use with Xenia by offering a graphical interface like the huge majority of emulators' GUIs do.

Kinda sad to see this rejected just like that, but you seem to have made up your mind so it is what it is.

Cheers.

**Comment by shazzaam7** [comment]
Don't necessarily see this as rejected. I'm keeping an eye on it and if I see more people request it I can easily implement it.

**Comment by Mahim2000** [comment]
> I have left that out because I thought most people play the games with a controller.

It might seem weird to you, but a lot of us do play Emulated games using Keyboard only. Specially when the game genre are mostly 2D, Racing, Platformers or Fighting.
Having to connect my dusty controller with my laptop just to play some "Neo Geo Battle Coliseum" while me not being accustomed to play Fighting Games on a Controller, really doesnt feel right to me, much like a lot of people around. Trust me.
