### ISSUE TITLE
uncapping the FPS is impossible

### ISSUE THREAD

**Issue by Joze53** [xenia-manager/xenia-manager#93]
**Describe the bug**
You use to be able to uncap the fps by disabling vsync, but now no matter what you do, it does not work, even forcing vsync to off doesn't work

**To Reproduce**
1. Go to 'xenia settings'
2. Click on 'vsync'
3. Scroll down to 'off'

**Expected behavior**
The Frame Rate will remain at 30 fps.

**Screenshots**
![Screenshot 2024-08-13 214533](https://github.com/user-attachments/assets/da0fec9c-5e4e-4e19-8968-92d17674577e)

**Additional context**
no matter the game the feature that worked previously, doesn't work anymore.

**Log File**
[xenia.log](https://github.com/user-attachments/files/16606781/xenia.log)

**Comment by shazzaam7** [comment]
Did you turn off Vsync in game profile or only in the default Xenia profile?

**Comment by ArtemGT69** [comment]
> Did you turn off Vsync in game profile or only in the default Xenia profile?

in xenia log file framerate limit is 60 fps so xenia use 30 fps if needed more it needs 120 fps for 60 fps in xenia and so on
but i guess he forget to check game config file in xenia manager

**Comment by shazzaam7** [comment]
Closing this issue due to lack of response.
