### ISSUE TITLE
Feature Request: add an icon option while editing the game.

### ISSUE THREAD

**Issue by A1eNaz** [xenia-manager/xenia-manager#94]
as title says, would like there to be an option for creating a shortcut to a game to use the icon instead of the cover.
also would like if the .ico format is supported.

how it looks like with icon:
![Icon](https://github.com/user-attachments/assets/83340f33-2ed2-41f6-aba4-cb4a78c0f570)

how it looks like with cover:
![Cover](https://github.com/user-attachments/assets/d206e77b-d7e6-45d9-9e93-d96b15a79e58)

**Comment by shazzaam7** [comment]
Yes, I'm currently working on trying to get another source that has icons apart from the Xbox Marketplace (LaunchBox right now is the main contender) to add a way of adding shortcut icon (Since both of those sources have either an icon or a disc made for that game).

**Comment by shazzaam7** [comment]
I have implemented this in the latest [experimental build](https://github.com/xenia-manager/xenia-manager/releases/tag/experimental). Feel free to test it and give me feedback.

**Comment by A1eNaz** [comment]
works like a charm alongside the launch argument.
very nice 👍
