### ISSUE TITLE
Switch to custom xenia doesn't disappear after it switched

### ISSUE THREAD

**Issue by ArtemGT69** [xenia-manager/xenia-manager#96]
**Describe the bug**
when you switch to custom xenia, button for switching xenia to custom xenia build doesn't disappear.

**To Reproduce**
1. Go to 'Edit Game'
2. Click on 'Switch to Custom Xenia'
3. Select Custom Xenia Build

**Expected behavior**
Button "Switch to Custom Xenia" should disappear after user choosed custom xenia.

**Screenshots**
This is what it should look like after you choose a custom build
![Xenia_Manager_s8JSbZzBF8](https://github.com/user-attachments/assets/a833277c-4305-489b-b51f-d10563983839)

**Additional context**
Video of Switch from default xenia to Custom Xenia Build

https://github.com/user-attachments/assets/e46a3a60-ec32-4636-a149-03214482c52d

**Log File**
[Log-20240816.txt](https://github.com/user-attachments/files/16636570/Log-20240816.txt)

**Comment by shazzaam7** [comment]
Oh no, this is intended. It's supposed to stay visible because you might have another build of xenia locally that you want to switch to.

**Comment by ArtemGT69** [comment]
> Oh no, this is intended. It's supposed to stay visible because you might have another build of xenia locally that you want to switch to.

oh so that's a reason why but for me i only use that button once and don't use it again

**Comment by shazzaam7** [comment]
It is for people who maybe have more than 1 build of Xenia so it's easier for them to switch them. Ignore it if that's the case.

**Comment by ArtemGT69** [comment]
> It is for people who maybe have more than 1 build of Xenia so it's easier for them to switch them. Ignore it if that's the case.

Okay sorry

**Comment by shazzaam7** [comment]
No need to apologize^^
